/**
 * The characters and abilities the rules read.
 *
 * This is generated by nobody. It is written by hand, committed to git, and
 * hashed into a version every match records, so a balance change is a pull
 * request with a diff and a match played last month still replays after it.
 *
 * Postgres stores what players did. Git stores what the game is.
 */

export type { Fighter } from "./characters.ts";
export { CAST, CONTENT_VERSION, ROSTER, squadsOf } from "./characters.ts";
